#ddev-generated
ARG SUPERCRONIC_VERSION=v0.2.48
ARG SUPERCRONIC_SHA1SUM_AMD64=016b7c9aebfc8d9fd9526e8ba33b191fc524485f
ARG SUPERCRONIC_SHA1SUM_ARM64=2ab9b3bdcf290f60b59700aad876b6e68f3a6b06

ARG TARGETARCH
RUN set -eux; \
    case "${TARGETARCH}" in \
        amd64) SHA="${SUPERCRONIC_SHA1SUM_AMD64}" ;; \
        arm64) SHA="${SUPERCRONIC_SHA1SUM_ARM64}" ;; \
        *) echo "Unsupported architecture: ${TARGETARCH}" && exit 1 ;; \
    esac; \
    curl -fsSL "https://github.com/aptible/supercronic/releases/download/${SUPERCRONIC_VERSION}/supercronic-linux-${TARGETARCH}" \
        -o /usr/local/bin/supercronic \
    && echo "${SHA}  /usr/local/bin/supercronic" | sha1sum -c - \
    && chmod +x /usr/local/bin/supercronic

RUN mkdir -p /etc/supercronic
COPY ./*.cron /etc/supercronic/
RUN cat /etc/supercronic/*.cron > /etc/supercronic/crontab

COPY ./supercronic.conf /etc/supervisor/conf.d/supercronic.conf
