#ddev-generated
ARG SUPERCRONIC_VERSION=v0.2.49
ARG SUPERCRONIC_SHA1SUM_AMD64=e63c11a9726b775a6a11801e81af4f3fb926aa68
ARG SUPERCRONIC_SHA1SUM_ARM64=0b6c5bb743e0b0dafed1132198c81807927ac413

ARG TARGETARCH
RUN set -eux; \
    case "${TARGETARCH}" in \
        amd64) SHA="${SUPERCRONIC_SHA1SUM_AMD64}" ;; \
        arm64) SHA="${SUPERCRONIC_SHA1SUM_ARM64}" ;; \
        *) echo "Unsupported architecture: ${TARGETARCH}" && exit 1 ;; \
    esac; \
    curl -fsSL "https://github.com/aptible/supercronic/releases/download/${SUPERCRONIC_VERSION}/supercronic-linux-${TARGETARCH}" \
        -o /usr/local/bin/supercronic \
    && echo "${SHA}  /usr/local/bin/supercronic" | sha1sum -c - \
    && chmod +x /usr/local/bin/supercronic

RUN mkdir -p /etc/supercronic
COPY ./*.cron /etc/supercronic/
RUN cat /etc/supercronic/*.cron > /etc/supercronic/crontab

COPY ./supercronic.conf /etc/supervisor/conf.d/supercronic.conf
